complexity:
  ComplexCondition:
    threshold: 3
  ComplexInterface:
    threshold: 8
  ComplexMethod:
    threshold: 10
  LargeClass:
    threshold: 400
  LongMethod:
    threshold: 40
  LongParameterList:
    functionThreshold: 4
    constructorThreshold: 8
  MethodOverloading:
    threshold: 5
  TooManyFunctions:
    thresholdInFiles: 10
    thresholdInClasses: 10
    thresholdInInterfaces: 10
    thresholdInObjects: 10
    thresholdInEnums: 10
